# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  jobs:
    post_checkout:
      - git fetch --unshallow || true

python:
  install:
    - requirements: doc/manual/requirements.txt

sphinx:
  configuration: doc/manual/conf.py

formats:
  - pdf
